// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogtvcqyoskodixbetoww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndHZjcXlvc2tvZGl4YmV0b3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTY0MjYsImV4cCI6MjA2NDk5MjQyNn0.ZAJdTMGfWqXk60fLzhLFoAzId_hL10WcjNVTfg8FkMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);